# Generated by Django 4.2 on 2023-05-02 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Type is active')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Amount')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('btype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.billingtype')),
            ],
        ),
    ]
