# Generated by Django 4.2 on 2023-04-12 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='btype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.billingtype'),
        ),
        migrations.AddField(
            model_name='billing',
            name='paid',
            field=models.BooleanField(default=True, verbose_name='Paid'),
        ),
    ]
