# Generated by Django 4.2 on 2023-04-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_billing_amount_billing_btype_billing_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
    ]
