# Generated by Django 4.2 on 2023-05-13 01:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='Price')),
                ('naration', models.TextField(blank=True, null=True, verbose_name='Naration')),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('dafault_range', models.TextField(blank=True, null=True, verbose_name='Default Range')),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='Price')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(blank=True, null=True, verbose_name='Updated on')),
                ('has_subtest', models.BooleanField(default=False, verbose_name='Has Sub Test')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_category', to='lab.testcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SubTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('dafault_range', models.TextField(blank=True, null=True, verbose_name='Default Range')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.labtest')),
            ],
        ),
        migrations.CreateModel(
            name='SubTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Result')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(blank=True, null=True, verbose_name='Updated on')),
                ('subtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.subtest')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.TextField(blank=True, null=True, verbose_name='Test Results')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(blank=True, null=True, verbose_name='Updated on')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.assignedtest')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='handled',
            field=models.BooleanField(default=False, verbose_name='Handled'),
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='assignedtest',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.request'),
        ),
        migrations.AddField(
            model_name='assignedtest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.labtest'),
        ),
    ]
