# Generated by Django 4.2 on 2023-05-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_requestcategory_request_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='currency',
            field=models.CharField(default='UGX', max_length=5, verbose_name='Currency'),
        ),
    ]
