# Generated by Django 4.2 on 2023-07-12 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_alter_allergy_options_alter_generalfinding_options_and_more'),
        ('doctor', '0002_alter_doctor_nin'),
        ('lab', '0004_labtest_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_category', to='lab.requestcategory'),
        ),
        migrations.AlterField(
            model_name='request',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='request',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.visit'),
        ),
    ]
