# Generated by Django 4.2 on 2023-07-12 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctor_nin'),
        ('patients', '0014_visit_visit_id'),
        ('lab', '0005_alter_request_category_alter_request_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='attendant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendant', to='doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_category', to='lab.requestcategory'),
        ),
        migrations.AlterField(
            model_name='request',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='request',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.visit'),
        ),
    ]
