# Generated by Django 4.2 on 2023-07-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_alter_request_attendant_alter_request_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignedtest',
            options={'ordering': ('-id', '-updated_on')},
        ),
        migrations.AlterModelOptions(
            name='labtest',
            options={'ordering': ('-id', '-updated_on')},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ('-id', '-updated_on')},
        ),
        migrations.AlterModelOptions(
            name='subtestresult',
            options={'ordering': ('-id', '-updated_on')},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ('-id', '-updated_on')},
        ),
        migrations.AddField(
            model_name='assignedtest',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated on'),
        ),
    ]
