# Generated by Django 4.2 on 2023-08-02 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_alter_assignedtest_options_alter_labtest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtest',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lab.request'),
        ),
    ]
