# Generated by Django 4.2 on 2023-05-02 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=256, verbose_name='First Name')),
                ('middlename', models.CharField(blank=True, max_length=256, null=True, verbose_name='Middle Name')),
                ('lastname', models.CharField(max_length=256, verbose_name='Last Name')),
                ('age', models.IntegerField(blank=True, default=0, null=True, verbose_name='Age')),
                ('date_of_birth', models.DateTimeField(blank=True, null=True, verbose_name='Date of Birth')),
                ('nin', models.CharField(blank=True, max_length=256, null=True, verbose_name='National Identification Number')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=256, verbose_name='Gender')),
                ('telnumber', models.CharField(max_length=256, verbose_name='Phone Number')),
                ('alttelnumber', models.CharField(blank=True, max_length=256, null=True, verbose_name='Alternative Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Address')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Safe Url')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(blank=True, null=True, verbose_name='Updated on')),
                ('speciality', models.ManyToManyField(related_name='doctor_speciality', to='doctor.doctorspeciality')),
            ],
            options={
                'ordering': ('-id', '-updated_on'),
                'abstract': False,
            },
        ),
    ]
