# Generated by Django 4.2 on 2023-05-02 10:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('doctor', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=256, verbose_name='First Name')),
                ('middlename', models.CharField(blank=True, max_length=256, null=True, verbose_name='Middle Name')),
                ('lastname', models.CharField(max_length=256, verbose_name='Last Name')),
                ('age', models.IntegerField(blank=True, default=0, null=True, verbose_name='Age')),
                ('date_of_birth', models.DateTimeField(blank=True, null=True, verbose_name='Date of Birth')),
                ('nin', models.CharField(blank=True, max_length=256, null=True, verbose_name='National Identification Number')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=256, verbose_name='Gender')),
                ('telnumber', models.CharField(max_length=256, verbose_name='Phone Number')),
                ('alttelnumber', models.CharField(blank=True, max_length=256, null=True, verbose_name='Alternative Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Address')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Safe Url')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(blank=True, null=True, verbose_name='Updated on')),
                ('patient_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='relationship')),
            ],
            options={
                'ordering': ('-id', '-updated_on'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False, verbose_name='Completed')),
                ('updated_on', models.DateTimeField(blank=True, null=True, verbose_name='Updated on')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('billing', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.billing')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.visitcategory')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('speciality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctorspeciality')),
            ],
            options={
                'ordering': ('-id', '-updated_on'),
            },
        ),
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(blank=True, max_length=256, null=True, verbose_name='Blood Pressure')),
                ('heart_rate', models.CharField(blank=True, max_length=256, null=True, verbose_name='Heart Rate')),
                ('respiratory_rate', models.CharField(blank=True, max_length=256, null=True, verbose_name='Respiratory Rate')),
                ('temperature', models.CharField(blank=True, max_length=256, null=True, verbose_name='Temperature')),
                ('sign_symptoms', models.TextField(blank=True, null=True, verbose_name='Signs and Symptoms')),
                ('injury_details', models.TextField(blank=True, null=True, verbose_name='injury Details')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(blank=True, null=True, verbose_name='Updated on')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.visit')),
            ],
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=256, verbose_name='First Name')),
                ('middlename', models.CharField(blank=True, max_length=256, null=True, verbose_name='Middle Name')),
                ('lastname', models.CharField(max_length=256, verbose_name='Last Name')),
                ('age', models.IntegerField(blank=True, default=0, null=True, verbose_name='Age')),
                ('date_of_birth', models.DateTimeField(blank=True, null=True, verbose_name='Date of Birth')),
                ('nin', models.CharField(blank=True, max_length=256, null=True, verbose_name='National Identification Number')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=256, verbose_name='Gender')),
                ('telnumber', models.CharField(max_length=256, verbose_name='Phone Number')),
                ('alttelnumber', models.CharField(blank=True, max_length=256, null=True, verbose_name='Alternative Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Address')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='Safe Url')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(blank=True, null=True, verbose_name='Updated on')),
                ('relationship', models.CharField(max_length=256, verbose_name='relationship')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='patients.patient')),
            ],
            options={
                'ordering': ('-id', '-updated_on'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('comments', models.TextField(blank=True, null=True, verbose_name="Doctor's Comments")),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(blank=True, null=True, verbose_name='Updated on')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.visit')),
            ],
        ),
    ]
