# Generated by Django 4.2 on 2023-04-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='lastname',
            field=models.CharField(max_length=256, verbose_name='Last Name'),
        ),
    ]
