# Generated by Django 4.2 on 2023-05-03 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('patients', '0004_alter_triage_muac_alter_triage_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='billing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.billing'),
        ),
    ]
