# Generated by Django 4.2 on 2023-05-09 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_visit_billing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergy',
            old_name='comments',
            new_name='comment',
        ),
    ]
