# Generated by Django 4.2 on 2023-05-09 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_rename_comments_allergy_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergy',
            name='visit',
        ),
        migrations.AddField(
            model_name='allergy',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
            preserve_default=False,
        ),
    ]
