# Generated by Django 4.2 on 2023-04-07 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_doctorspeciality_doctor_speciality'),
        ('patients', '0007_nextofkin_updated_on_patient_updated_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.doctor'),
        ),
        migrations.AddField(
            model_name='visit',
            name='patient',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.doctorspeciality'),
        ),
    ]
