# Generated by Django 4.2 on 2023-04-07 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_visit_doctor_visit_patient_visit_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Created on'),
        ),
        migrations.AddField(
            model_name='visit',
            name='updated_on',
            field=models.DateField(blank=True, null=True, verbose_name='Updated on'),
        ),
    ]
