# Generated by Django 4.2 on 2023-05-12 23:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_nextofkin_nin_alter_patient_nin'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenting_complaints', models.CharField(blank=True, max_length=256, null=True, verbose_name='presenting complaints')),
                ('clinical_notes', models.CharField(blank=True, max_length=256, null=True, verbose_name='clinical notes')),
                ('rohs', models.CharField(blank=True, max_length=256, null=True, verbose_name='rohs')),
                ('psh', models.CharField(blank=True, max_length=256, null=True, verbose_name='psh')),
                ('poh', models.CharField(blank=True, max_length=256, null=True, verbose_name='poh')),
                ('cvs', models.CharField(blank=True, max_length=256, null=True, verbose_name='cvs')),
                ('general_appearance', models.CharField(blank=True, max_length=256, null=True, verbose_name='general appearance')),
                ('respiratory', models.CharField(blank=True, max_length=256, null=True, verbose_name='respiratory')),
                ('ent', models.CharField(blank=True, max_length=256, null=True, verbose_name='ent')),
                ('abdomen_and_Gut', models.CharField(blank=True, max_length=256, null=True, verbose_name='abdomen and Gut')),
                ('cns', models.CharField(blank=True, max_length=256, null=True, verbose_name='cns')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(blank=True, null=True, verbose_name='Updated on')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
