# Generated by Django 4.2 on 2023-04-12 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_billing_paid'),
        ('patients', '0009_visit_created_on_visit_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='billing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.billing'),
        ),
    ]
