# Generated by Django 4.2 on 2023-05-13 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_labrequest_labtestcategory_labtest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='request',
        ),
        migrations.DeleteModel(
            name='LabRequest',
        ),
        migrations.DeleteModel(
            name='LabTest',
        ),
        migrations.DeleteModel(
            name='LabTestCategory',
        ),
    ]
