# Generated by Django 4.2 on 2023-04-12 22:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_visit_billing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(blank=True, max_length=256, null=True, verbose_name='Blood Pressure')),
                ('heart_rate', models.CharField(blank=True, max_length=256, null=True, verbose_name='Heart Rate')),
                ('respiratory_rate', models.CharField(blank=True, max_length=256, null=True, verbose_name='Respiratory Rate')),
                ('temperature', models.CharField(blank=True, max_length=256, null=True, verbose_name='Temperature')),
                ('sign_symptoms', models.TextField(blank=True, null=True, verbose_name='Signs and Symptoms')),
                ('injury_details', models.TextField(blank=True, null=True, verbose_name='injury Details')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_on', models.DateField(blank=True, null=True, verbose_name='Updated on')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.visit')),
            ],
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Name')),
                ('comments', models.TextField(blank=True, null=True, verbose_name="Doctor's Comments")),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_on', models.DateField(blank=True, null=True, verbose_name='Updated on')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.visit')),
            ],
        ),
    ]
