# Generated by Django 4.2 on 2023-07-12 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_remove_labtest_category_remove_labtest_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalfinding',
            name='patient',
        ),
        migrations.AddField(
            model_name='generalfinding',
            name='eye',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='eye'),
        ),
        migrations.AddField(
            model_name='generalfinding',
            name='muscular_skeletal',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='muscular skeletal'),
        ),
        migrations.AddField(
            model_name='generalfinding',
            name='provisional_status',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='provisional status'),
        ),
        migrations.AddField(
            model_name='generalfinding',
            name='psychological_status',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='psychological status'),
        ),
        migrations.AddField(
            model_name='generalfinding',
            name='pv_pr',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='pv/pr'),
        ),
        migrations.AddField(
            model_name='generalfinding',
            name='skin',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='skin'),
        ),
        migrations.AddField(
            model_name='generalfinding',
            name='treatment_plan',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='treatment plan'),
        ),
        migrations.AddField(
            model_name='generalfinding',
            name='visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.visit'),
            preserve_default=False,
        ),
    ]
