# Generated by Django 4.2 on 2023-04-17 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_nextofkin_age_nextofkin_date_of_birth_patient_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated on'),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated on'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated on'),
        ),
        migrations.AlterField(
            model_name='triage',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='triage',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated on'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated on'),
        ),
    ]
