# Generated by Django 4.2 on 2023-07-12 13:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_remove_generalfinding_patient_generalfinding_eye_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergy',
            options={'ordering': ('-id', '-updated_on')},
        ),
        migrations.AlterModelOptions(
            name='generalfinding',
            options={'ordering': ('-id', '-updated_on')},
        ),
        migrations.AlterModelOptions(
            name='triage',
            options={'ordering': ('-id', '-updated_on')},
        ),
        migrations.CreateModel(
            name='PaedeatricNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=256, null=True, verbose_name='notes')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(blank=True, null=True, verbose_name='Updated on')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.visit')),
            ],
            options={
                'ordering': ('-id', '-updated_on'),
            },
        ),
        migrations.CreateModel(
            name='GynNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=256, null=True, verbose_name='notes')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(blank=True, null=True, verbose_name='Updated on')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.visit')),
            ],
            options={
                'ordering': ('-id', '-updated_on'),
            },
        ),
    ]
