# Generated by Django 4.2 on 2023-04-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_alter_allergy_created_on_alter_allergy_updated_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
    ]
