# Generated by Django 4.2 on 2023-07-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_alter_allergy_options_alter_generalfinding_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visit_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Visit Id'),
        ),
    ]
