# Generated by Django 4.2 on 2023-04-17 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_visit_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='category',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
