# Generated by Django 4.2 on 2023-04-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NextOfKin',
        ),
    ]
