# Generated by Django 4.2 on 2023-04-17 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_doctor_age_doctor_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Updated on'),
        ),
    ]
